global:
    scrape_interval:     10s
    evaluation_interval: 30s
    # scrape_timeout is set to the global default (10s).
  
scrape_configs:
- job_name: wim
  scheme: http
  static_configs:
  - targets:
    - 10.30.0.168:8888
- job_name: katana
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
  